### ISSUE TITLE
IndexError: list index out of range  CM error: Portable CM script failed (name = process-mlperf-accuracy, return code = 256)

### ISSUE THREAD

**Issue by silhouette001** [mlcommons/ck#584]
Encountered this error while running the command,

```
cm run script "app mlperf inference generic _python _retinanet _onnxruntime _cpu"
--scenario=Offline
--mode=accuracy
--test_query_count=10
 --rerun
```

The image of output with error:
![IMG-20221211-WA0007](https://user-images.githubusercontent.com/84288594/207265076-52b36c99-21da-4a29-88c3-a6534e7b4676.jpeg)

The complete output after execution:
[Output.txt](https://github.com/mlcommons/ck/files/10215905/Output.txt)

**Comment by arjunsuresh** [comment]
Hi @silhouette001 , thank you for reporting this issue. It should be fixed in the master branch now. Can you please do 
```
cm pull repo mlcommons@ck
```
and then redo the command?

**Comment by gfursin** [comment]
You may also need to clean the CM cache if error is still there:
```bash
cm rm cache -f
```

**Comment by arjunsuresh** [comment]
As discussed over the call this issue is now solved. Hence closing this.
